server:
  port: ${PORT:8761}

spring:
  application:
    name: MEDICAL-SERVER

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
  server:
    wait-time-in-ms-when-sync-empty: 0