spring:
  application:
    name: PAYMENT-SERVICE
    
  config:
    import: optional:configserver:http://localhost:8086
  
 
#eureka:
#  instance:
#    #lease-renewal-interval-in-seconds: 1
#    #lease-expiration-duration-in-seconds: 2
#    hostname: localhost
#  client:
#    service-url:
#       defaultZone: http://localhost:8761/eureka/
#    healthcheck:
#      enabled: true
#    lease:
#      duration:5
  

    
management:
  security:
    enabled: false
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
       
  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances: 
      EMAIL-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

