eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
    
spring:
  application:
    name: PatientMs
    
management:
  security:
    enabled: false
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
       
  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances: 
      ServiceMs:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      userService:
        maxRetryAttempts: 5
        waitDuration: 10s
        
        
        
        
