server:
  port: 8085

spring:
  application:
    name: API-GATWAY
  
  cloud:
    gateway:
      routes:
        - id: REGISTRATION-SERVICE
          uri: lb://REGISTRATION-SERVICE
          predicates: 
            - Path= /api/v1/**
            
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates: 
            - Path= /**
    
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
