spring:
  application:
    name: REGISTRATION-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: upload02.sdcard@gmail.com
    password: ngoghqgehuducxqf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
eureka:
  instance:
    #lease-renewal-interval-in-seconds: 1
    #lease-expiration-duration-in-seconds: 2
    hostname: localhost
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration:5
  

management:
  security:
    enabled: false
    
